export const meetingNames = [
    'Bay Sheffield',
    'Brighton',
    'Pre Bay Sheffield',
    'Kensington',
    'Flinders',
    'McKinnon Parade',
    'Loxton',
    'Flagstaff',
    'Camden',
    'Fleurieu Milk',
    'Marion',
    'Mount Gambier',
    'Port Adelaide',
    'Sacred Heart',
    'Bowker Street',
    "St Michael's College",
    'Keith Aiston',
    'Hectorville',
    'Western Districts',
    'Tea Tree Gully',
    'Henley',
    'Whyalla',
    'Glenelg',
    'Reynella'
]
